version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: support_console
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - support-network

  app:
    build: .
    container_name: support-system
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/support_console
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: newpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 9590
    ports:
      - "9590:9590"
    networks:
      - support-network

volumes:
  postgres-data:

networks:
  support-network:
